branches:
  only:
    - master
    - feat/offline-only-index
osx_image: xcode9
language: objective-c
env:
  matrix:
    - FASTLANE_TARGET="mac"
    - FASTLANE_TARGET="ios"
    - FASTLANE_TARGET="tv"
install: true
before_script:
  - gem install xcpretty -N
  - gem update fastlane
script:
  - set -o pipefail
  - fastlane ${FASTLANE_TARGET} test
